### ISSUE TITLE
non-native Polymer problem

### ISSUE THREAD

**Issue by wasd171** [sindresorhus/domify#43]
Hi!

Using domify on Polymer custom element like `domify("<custom-element></custom-element>")` returns different results: in Chrome `innerHTML` is correct (due to native support) but Safari/Firefox return `innerHTML = ""`

domify needs to wait till the actual component render by `WebComponents` polyfill

**Comment by sindresorhus** [comment]
Closing as this is no longer relevant. Web Components are natively supported in browsers now.
